# Generated by Django 2.2.2 on 2019-07-13 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20190713_1049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_picture',
            field=models.ImageField(default='img.jpg', upload_to='images'),
        ),
    ]
