# Generated by Django 2.2.3 on 2019-07-17 06:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20190713_1110'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
        migrations.CreateModel(
            name='UserProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='media/images/<built-in function id>/')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='username', to='users.UserProfile')),
            ],
        ),
    ]
