# Generated by Django 2.2.3 on 2019-07-17 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20190717_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='image',
            field=models.ImageField(default='media/images/default.png', upload_to='media/images/<built-in function id>/'),
        ),
    ]
