# Generated by Django 2.2.2 on 2019-07-18 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20190717_1203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='image',
            field=models.ImageField(default='static/default.png', upload_to='static<built-in function id>/'),
        ),
    ]
