# Generated by Django 2.2.2 on 2019-07-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20190718_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='image',
            field=models.ImageField(default='static/default.png', upload_to='static/profile-pictures/<built-in function id>/'),
        ),
    ]
