# Generated by Django 2.2.2 on 2019-07-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20190718_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilepicture',
            name='image',
            field=models.ImageField(default='static/default.png', upload_to='static/profile-pictures/'),
        ),
    ]
